#include "SceneEditorPanel.hpp"

#include "SharedScene.hpp"

#include <osg/Group>

#include <QCoreApplication>
#include <QComboBox>
#include <QDialog>
#include <QDialogButtonBox>
#include <QDir>
#include <QDoubleSpinBox>
#include <QFile>
#include <QFileDialog>
#include <QFileInfo>
#include <QFormLayout>
#include <QHeaderView>
#include <QHideEvent>
#include <QHBoxLayout>
#include <QMessageBox>
#include <QRegularExpression>
#include <QShowEvent>
#include <QTableWidgetItem>
#include <QTextStream>
#include <QVBoxLayout>

namespace standalone_mvp {

namespace {

bool runPoseEditorDialog(QWidget* parent, const QString& title, std::array<double, 6>* pose) {
    if (!pose) {
        return false;
    }
    QDialog dlg(parent);
    dlg.setWindowTitle(title);
    dlg.resize(380, 300);
    auto* layout = new QVBoxLayout(&dlg);
    auto* form = new QFormLayout();
    QDoubleSpinBox* s[6];
    const QString labels[] = {QStringLiteral("X"), QStringLiteral("Y"), QStringLiteral("Z"),
                              QStringLiteral("Roll"), QStringLiteral("Pitch"), QStringLiteral("Yaw")};
    for (int i = 0; i < 6; ++i) {
        s[i] = new QDoubleSpinBox(&dlg);
        s[i]->setRange(-1.0e7, 1.0e7);
        s[i]->setDecimals(6);
        s[i]->setSingleStep(0.1);
        s[i]->setValue((*pose)[static_cast<std::size_t>(i)]);
        form->addRow(labels[i], s[i]);
    }
    layout->addLayout(form);
    auto* buttons = new QDialogButtonBox(QDialogButtonBox::Ok | QDialogButtonBox::Cancel, &dlg);
    QObject::connect(buttons, &QDialogButtonBox::accepted, &dlg, &QDialog::accept);
    QObject::connect(buttons, &QDialogButtonBox::rejected, &dlg, &QDialog::reject);
    layout->addWidget(buttons);
    if (dlg.exec() != QDialog::Accepted) {
        return false;
    }
    for (int i = 0; i < 6; ++i) {
        (*pose)[static_cast<std::size_t>(i)] = s[i]->value();
    }
    return true;
}

QString sanitizedModelName(QString name) {
    name = name.trimmed();
    name.replace(QRegularExpression(QStringLiteral("[^A-Za-z0-9_\\-]+")), QStringLiteral("_"));
    name.replace(QRegularExpression(QStringLiteral("_+")), QStringLiteral("_"));
    while (name.startsWith(QLatin1Char('_'))) {
        name.remove(0, 1);
    }
    while (name.endsWith(QLatin1Char('_'))) {
        name.chop(1);
    }
    if (name.isEmpty()) {
        name = QStringLiteral("imported_model");
    }
    return name;
}

QString buildModelConfigXml(const QString& model_name) {
    QString text;
    QTextStream out(&text);
    out << "<?xml version=\"1.0\"?>\n";
    out << "<model>\n";
    out << "  <name>" << model_name << "</name>\n";
    out << "  <version>1.0</version>\n";
    out << "  <sdf version=\"1.6\">model.sdf</sdf>\n";
    out << "  <author>\n";
    out << "    <name>EchoVerse Sonar Lab</name>\n";
    out << "    <email>noreply@echoverse.local</email>\n";
    out << "  </author>\n";
    out << "  <description>Imported model generated by Scene Editor.</description>\n";
    out << "</model>\n";
    return text;
}

QString buildModelSdfXml(const QString& model_name, const QString& mesh_file_name) {
    QString text;
    QTextStream out(&text);
    out << "<?xml version=\"1.0\" ?>\n";
    out << "<sdf version=\"1.6\">\n";
    out << "  <model name=\"" << model_name << "\">\n";
    out << "    <static>true</static>\n";
    out << "    <link name=\"link\">\n";
    out << "      <pose>0 0 0 0 0 0</pose>\n";
    out << "      <collision name=\"collision\">\n";
    out << "        <geometry>\n";
    out << "          <mesh>\n";
    out << "            <uri>model://" << model_name << "/meshs/" << mesh_file_name << "</uri>\n";
    out << "          </mesh>\n";
    out << "        </geometry>\n";
    out << "      </collision>\n";
    out << "      <visual name=\"visual\">\n";
    out << "        <geometry>\n";
    out << "          <mesh>\n";
    out << "            <uri>model://" << model_name << "/meshs/" << mesh_file_name << "</uri>\n";
    out << "          </mesh>\n";
    out << "        </geometry>\n";
    out << "      </visual>\n";
    out << "    </link>\n";
    out << "  </model>\n";
    out << "</sdf>\n";
    return text;
}

bool writeTextFileUtf8(const QString& file_path, const QString& content, QString* err) {
    QFile file(file_path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Truncate | QIODevice::Text)) {
        if (err) {
            *err = QStringLiteral("Failed to write file: %1").arg(file_path);
        }
        return false;
    }
    const QByteArray data = content.toUtf8();
    const qint64 written = file.write(data);
    file.close();
    if (written != data.size()) {
        if (err) {
            *err = QStringLiteral("Failed to write full file content: %1").arg(file_path);
        }
        return false;
    }
    return true;
}

} // namespace

SceneEditorPanel::SceneEditorPanel(QWidget* parent)
    : QWidget(parent) {
    auto* main = new QVBoxLayout(this);
    main->setContentsMargins(6, 6, 6, 6);
    main->setSpacing(6);
    hint_ = new QLabel(
        QStringLiteral("Editor opens in edit mode and pauses sonar updates until this window is closed."),
        this);
    hint_->setWordWrap(true);
    hint_->setStyleSheet(QStringLiteral("QLabel{color:#9fb6cc;font-size:11px;}"));
    table_ = new QTableWidget(this);
    table_->setMinimumWidth(640);
    table_->setColumnCount(7);
    table_->setHorizontalHeaderLabels({QStringLiteral("Model"), QStringLiteral("X"), QStringLiteral("Y"), QStringLiteral("Z"),
                                        QStringLiteral("Roll"), QStringLiteral("Pitch"), QStringLiteral("Yaw")});
    table_->setSelectionBehavior(QAbstractItemView::SelectRows);
    table_->setSelectionMode(QAbstractItemView::SingleSelection);
    table_->setEditTriggers(QAbstractItemView::NoEditTriggers);
    table_->verticalHeader()->setVisible(false);
    table_->horizontalHeader()->setSectionResizeMode(0, QHeaderView::Stretch);
    for (int i = 1; i < 7; ++i) {
        table_->horizontalHeader()->setSectionResizeMode(i, QHeaderView::ResizeToContents);
    }
    add_btn_ = new QPushButton(QStringLiteral("Add Model..."), this);
    edit_btn_ = new QPushButton(QStringLiteral("Edit Pose..."), this);
    del_btn_ = new QPushButton(QStringLiteral("Delete"), this);
    reload_btn_ = new QPushButton(QStringLiteral("Import Models"), this);
    const QString button_style = QStringLiteral(
        "QPushButton{"
        "border:1px solid #6f8aa6;"
        "border-radius:5px;"
        "padding:6px 10px;"
        "background:#203447;"
        "color:#eaf4ff;"
        "font-weight:600;"
        "}"
        "QPushButton:hover{background:#2a455d;}"
        "QPushButton:pressed{background:#1a2c3c;}"
        "QPushButton:disabled{border:1px solid #4d647b;background:#1c2630;color:#7f93a6;}");
    add_btn_->setStyleSheet(button_style);
    edit_btn_->setStyleSheet(button_style);
    del_btn_->setStyleSheet(button_style);
    reload_btn_->setStyleSheet(button_style);
    auto* row = new QHBoxLayout();
    row->addWidget(add_btn_);
    row->addWidget(edit_btn_);
    row->addWidget(del_btn_);
    main->addWidget(hint_);
    main->addWidget(table_, 1);
    main->addLayout(row);
    main->addWidget(reload_btn_);

    applyEnabledState();
    QObject::connect(add_btn_, &QPushButton::clicked, this, &SceneEditorPanel::onAddModel);
    QObject::connect(edit_btn_, &QPushButton::clicked, this, &SceneEditorPanel::onEditPose);
    QObject::connect(del_btn_, &QPushButton::clicked, this, &SceneEditorPanel::onDeleteModel);
    QObject::connect(reload_btn_, &QPushButton::clicked, this, &SceneEditorPanel::onImportModels);
}

void SceneEditorPanel::showEvent(QShowEvent* event) {
    QWidget::showEvent(event);
    setEditMode(true);
}

void SceneEditorPanel::hideEvent(QHideEvent* event) {
    QWidget::hideEvent(event);
    setEditMode(false);
}

void SceneEditorPanel::setEditMode(bool on) {
    if (edit_mode_active_ == on) {
        return;
    }
    edit_mode_active_ = on;
    if (pause_sonar_) {
        pause_sonar_(on);
    }
    applyEnabledState();
}

void SceneEditorPanel::applyEnabledState() {
    const bool ok = edit_mode_active_ && !world_path_.isEmpty() && world_models_;
    table_->setEnabled(ok);
    add_btn_->setEnabled(ok);
    edit_btn_->setEnabled(ok);
    del_btn_->setEnabled(ok);
    reload_btn_->setEnabled(ok);
}

void SceneEditorPanel::setWorldFile(const QString& absolute_world_path, const QString& world_spec_for_osg) {
    world_path_ = absolute_world_path;
    world_spec_osg_ = world_spec_for_osg;
    entries_.clear();
    if (!world_path_.isEmpty() && QFile::exists(world_path_)) {
        QString err;
        loadWorldIncludes(world_path_, &entries_, &err);
    }
    refreshTable();
    applyEnabledState();
}

void SceneEditorPanel::setWorldModelsGroup(osg::Group* world_models, float range_m) {
    world_models_ = world_models;
    range_m_ = range_m;
    applyEnabledState();
}

void SceneEditorPanel::setPauseSonarCallback(std::function<void(bool)> fn) {
    pause_sonar_ = std::move(fn);
}

void SceneEditorPanel::setProjectRoot(const QString& project_root) {
    project_root_ = project_root.trimmed();
}

void SceneEditorPanel::refreshTable() {
    table_->setRowCount(0);
    for (int i = 0; i < entries_.size(); ++i) {
        const WorldIncludeEntry& e = entries_[i];
        const int row = table_->rowCount();
        table_->insertRow(row);
        table_->setItem(row, 0, new QTableWidgetItem(e.model_name));
        for (int c = 0; c < 6; ++c) {
            table_->setItem(row, c + 1, new QTableWidgetItem(QString::number(e.pose[static_cast<std::size_t>(c)], 'g', 6)));
        }
    }
}

bool SceneEditorPanel::saveEntriesToDisk(QString* err) {
    if (world_path_.isEmpty()) {
        if (err) {
            *err = QStringLiteral("World file path is not set.");
        }
        return false;
    }
    return saveWorldIncludes(world_path_, entries_, err);
}

void SceneEditorPanel::reloadSceneGraph() {
    if (!world_models_ || world_spec_osg_.isEmpty()) {
        return;
    }
    rebuildWorldModelsFromWorldSpec(world_models_, range_m_, world_spec_osg_.toUtf8().constData());
}

void SceneEditorPanel::onAddModel() {
    if (!edit_mode_active_) {
        return;
    }
    const QStringList models = discoverSdfModelNames(project_root_);
    if (models.isEmpty()) {
        QMessageBox::warning(this, QStringLiteral("Warning"), QStringLiteral("No models were found under uwmodels/sdf."));
        return;
    }
    QDialog dlg(this);
    dlg.setWindowTitle(QStringLiteral("Add Model"));
    auto* layout = new QVBoxLayout(&dlg);
    auto* form = new QFormLayout();
    auto* combo = new QComboBox(&dlg);
    for (const QString& m : models) {
        combo->addItem(m);
    }
    form->addRow(QStringLiteral("Model"), combo);
    QDoubleSpinBox* sp[6];
    const QString labels[] = {QStringLiteral("X"), QStringLiteral("Y"), QStringLiteral("Z"),
                              QStringLiteral("Roll"), QStringLiteral("Pitch"), QStringLiteral("Yaw")};
    for (int i = 0; i < 6; ++i) {
        sp[i] = new QDoubleSpinBox(&dlg);
        sp[i]->setRange(-1.0e7, 1.0e7);
        sp[i]->setDecimals(6);
        sp[i]->setSingleStep(0.1);
        sp[i]->setValue(0.0);
        form->addRow(labels[i], sp[i]);
    }
    layout->addLayout(form);
    auto* buttons = new QDialogButtonBox(QDialogButtonBox::Ok | QDialogButtonBox::Cancel, &dlg);
    QObject::connect(buttons, &QDialogButtonBox::accepted, &dlg, &QDialog::accept);
    QObject::connect(buttons, &QDialogButtonBox::rejected, &dlg, &QDialog::reject);
    layout->addWidget(buttons);
    if (dlg.exec() != QDialog::Accepted) {
        return;
    }
    WorldIncludeEntry ent;
    ent.model_name = combo->currentText().trimmed();
    for (int i = 0; i < 6; ++i) {
        ent.pose[static_cast<std::size_t>(i)] = sp[i]->value();
    }
    if (ent.model_name.isEmpty()) {
        return;
    }
    entries_.push_back(ent);
    QString err;
    if (!saveEntriesToDisk(&err)) {
        entries_.pop_back();
        QMessageBox::critical(this, QStringLiteral("Error"), err);
        return;
    }
    reloadSceneGraph();
    refreshTable();
    emit sceneContentChanged();
}

void SceneEditorPanel::onEditPose() {
    if (!edit_mode_active_) {
        return;
    }
    const int row = table_->currentRow();
    if (row < 0 || row >= entries_.size()) {
        QMessageBox::information(this, QStringLiteral("Notice"), QStringLiteral("Please select one row first."));
        return;
    }
    std::array<double, 6> pose = entries_[row].pose;
    if (!runPoseEditorDialog(this, QStringLiteral("Pose — %1").arg(entries_[row].model_name), &pose)) {
        return;
    }
    entries_[row].pose = pose;
    QString err;
    if (!saveEntriesToDisk(&err)) {
        QMessageBox::critical(this, QStringLiteral("Error"), err);
        return;
    }
    reloadSceneGraph();
    refreshTable();
    emit sceneContentChanged();
}

void SceneEditorPanel::onDeleteModel() {
    if (!edit_mode_active_) {
        return;
    }
    const int row = table_->currentRow();
    if (row < 0 || row >= entries_.size()) {
        QMessageBox::information(this, QStringLiteral("Notice"), QStringLiteral("Please select a row to delete."));
        return;
    }
    const auto r = QMessageBox::question(this, QStringLiteral("Confirm"), QStringLiteral("Remove this model from the world file?"));
    if (r != QMessageBox::Yes) {
        return;
    }
    entries_.removeAt(row);
    QString err;
    if (!saveEntriesToDisk(&err)) {
        QMessageBox::critical(this, QStringLiteral("Error"), err);
        return;
    }
    reloadSceneGraph();
    refreshTable();
    emit sceneContentChanged();
}

void SceneEditorPanel::onImportModels() {
    if (!edit_mode_active_) {
        return;
    }
    if (project_root_.isEmpty()) {
        QMessageBox::warning(this, QStringLiteral("Warning"),
                             QStringLiteral("Project root is not set, cannot import models."));
        return;
    }
    const QString import_root = QDir(project_root_).filePath(QStringLiteral("uwmodels/sdf"));
    if (!QDir().mkpath(import_root)) {
        QMessageBox::warning(this, QStringLiteral("Warning"),
                             QStringLiteral("Failed to create import directory:\n%1").arg(import_root));
        return;
    }

    const QStringList model_files = QFileDialog::getOpenFileNames(
        this,
        QStringLiteral("Import Model Files"),
        QDir::homePath(),
        QStringLiteral("Model Files (*.obj *.stl *.dae *.osgb *.ply *.fbx *.gltf *.glb *.osg);;All Files (*.*)"));
    if (model_files.isEmpty()) {
        return;
    }

    QStringList imported_models;
    QStringList errors;
    for (const QString& src_path : model_files) {
        const QFileInfo src_info(src_path);
        if (!src_info.exists() || !src_info.isFile()) {
            errors << QStringLiteral("Source file is missing: %1").arg(src_path);
            continue;
        }
        const QString model_name = sanitizedModelName(src_info.completeBaseName());
        const QString model_dir = QDir(import_root).filePath(model_name);
        const QString meshs_dir = QDir(model_dir).filePath(QStringLiteral("meshs"));
        const QString dst_mesh = QDir(meshs_dir).filePath(src_info.fileName());
        const QString model_sdf = QDir(model_dir).filePath(QStringLiteral("model.sdf"));
        const QString model_config = QDir(model_dir).filePath(QStringLiteral("model.config"));

        if (QDir(model_dir).exists()) {
            const auto answer = QMessageBox::question(
                this,
                QStringLiteral("Overwrite Model"),
                QStringLiteral("Model folder already exists:\n%1\nOverwrite files for model '%2'?")
                    .arg(model_dir, model_name),
                QMessageBox::Yes | QMessageBox::No | QMessageBox::Cancel,
                QMessageBox::No);
            if (answer == QMessageBox::Cancel) {
                break;
            }
            if (answer == QMessageBox::No) {
                continue;
            }
        }

        if (!QDir().mkpath(meshs_dir)) {
            errors << QStringLiteral("Failed to create folder: %1").arg(meshs_dir);
            continue;
        }
        if (QFile::exists(dst_mesh)) {
            QFile::remove(dst_mesh);
        }
        if (!QFile::copy(src_path, dst_mesh)) {
            errors << QStringLiteral("Failed to copy model file to: %1").arg(dst_mesh);
            continue;
        }

        QString io_error;
        if (!writeTextFileUtf8(model_config, buildModelConfigXml(model_name), &io_error)) {
            errors << io_error;
            continue;
        }
        if (!writeTextFileUtf8(model_sdf, buildModelSdfXml(model_name, src_info.fileName()), &io_error)) {
            errors << io_error;
            continue;
        }
        imported_models << model_name;
    }

    if (!errors.isEmpty()) {
        QMessageBox::warning(this, QStringLiteral("Import Models"),
                             QStringLiteral("Some models failed to import:\n%1").arg(errors.join(QStringLiteral("\n"))));
    }
    if (!imported_models.isEmpty()) {
        QMessageBox::information(
            this, QStringLiteral("Import Models"),
            QStringLiteral("Imported %1 model(s) to:\n%2\n\n%3")
                .arg(imported_models.size())
                .arg(import_root)
                .arg(imported_models.join(QStringLiteral(", "))));
    }
}

} // namespace standalone_mvp
